version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    working_dir: /app
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    volumes:
      - .:/app
    links:
      - db
  db:
    image: mongo:3.6